### PR TITLE
feat(delayed job): allow to select the modules as part of the jobs name

### PR DESCRIPTION
**Pull request by martinramirez7**
This PR allows to use modules as part of jobs names on delayed jobs metrics.

This is useful in apps with several namespaces where each defines the same set of jobs, all running in the same queue, which is our situation.

It ensures backwards compatibility.

### CODE REVIEW

**Comment by martinramirez7** [comment]
Hey @SamSaffron, can you take a quick look of this please? It seems linter is failing on unchanged files

**Comment by SamSaffron** [comment]
any chance you can add a test to properly clarify new behavior ?

**Comment by martinramirez7** [comment]
Hey Sam, just added the new param to some tests. I don't really understand why the CI's tests are failing, any idea? locally works fine. I believe it has nothing to do with my changes. let me know if I'm wrong

**Comment by martinramirez7** [comment]
@SamSaffron I added a commit that fixes the CI problem with @blackjid suggestion. The problem is due json 2.7.2 doesn't load open struct library by default as it was on 2.7.1. you can see this [PR](https://github.com/flori/json/pull/565) for mor info

**Comment by martinramirez7** [comment]
hey @SamSaffron friendly reminder of this PR

**Comment by blackjid** [comment]
@SamSaffron any chance to merge and release this? That would be awesome

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
thanks ! merged.

**Pull request merged**
