### PR TITLE
Update README to note that default_labels & default_prefix works only on

### PR DESCRIPTION
**Pull request by yosiat**
single process mode

I tested this only on Single Process mode which there it works fine.

About the multi-process mode: I am not sure how to implement this, I don't see a global way of adding all metrics  & instrumentation (like process/middleware), maybe sending to prometheus_exporter in addition to metric values to send "default_labels" ?

### CODE REVIEW

**Comment by SamSaffron** [comment]
cool! thanks!

**Comment by yosiat** [comment]
@SamSaffron do you have any idea on how can I implement `default_labels` with multi-process support?

**Comment by SamSaffron** [comment]
cool, sure this is how I would do it

https://github.com/discourse/prometheus_exporter/blob/master/bin/prometheus_exporter#L21-L23 

we need another command line option

**Comment by yosiat** [comment]
The command line option won't work on my deployment.
I want to set-up one prometheus_exporter for all instances

**Pull request merged**
