### PR TITLE
Feature: Add Dalli::Client memcache metrics for web_collector

### PR DESCRIPTION
**Pull request by Subramanya-Murugesan**
Adds memcache metrics to HTTP requests

image (21)

### CODE REVIEW

**Comment by Subramanya-Murugesan** [comment]
Hey @SamSaffron , would you please take a look at this?

**Comment by Subramanya-Murugesan** [comment]
@SamSaffron could you please check this?

**Comment by Subramanya-Murugesan** [comment]
@SamSaffron Could you please have a look at this?

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
Thanks and sorry for the delay here, looks good!

**Pull request merged**
