### PR TITLE
FEATURE: add customizable labels option to puma collector (#172)

### PR DESCRIPTION
**Pull request by codez**
As discussed in #172, a basic implementation to add customizable labels for the puma collector.

### CODE REVIEW

**Comment by SamSaffron** [comment]
One more tiny thing and we can merge. 

Can you review the README and make sure it covers how to use this?

**Comment by codez** [comment]
I added a short note similar to other collectors.

**Comment by SamSaffron** [comment]
Oh I merged in the wrong order, can you rebase?

**Comment by codez** [comment]
There was no order, just changes in the same lines. I've rebased.

**Comment by SamSaffron** [comment]
cool! looks good!

**Pull request merged**
