### PR TITLE
Expand usage of MetricsContainer in other collectors

### PR DESCRIPTION
**Pull request by sosedoff**
Implements the MetricsContainer where applicable

### CODE REVIEW

**Comment by sosedoff** [comment]
@SamSaffron any thoughts? do we need extra tests?

**Comment by SamSaffron** [comment]
it looks great to me... but yeah I think we should have an integration test on each of these to ensure we did not regress. 

Kind of slack we did not have the tests to start with ... process collector at least has some coverage.

Do you think I should hold off merging till we have better coverage everywhere or should we merge and revisit tests? I am open to either.. The refactor is great.

**Comment by sosedoff** [comment]
Yea i'd add extra tests before merging to prevent any potential breakage.

**Comment by sosedoff** [comment]
@SamSaffron please have a look around, leave feedback. Im back to wrap this PR up since it has a lot of fixes and improvements. I've got a few more tests to add but i think its already pretty solid as is.

**Comment by SamSaffron** [comment]
Nice this is looking quite tidy! finding it hard to find any things to change

**Review by SamSaffron — APPROVED** [review]

**Pull request merged**
