### PR TITLE
Pass msg hash to Sidekiq jobs custom_labels function

### PR DESCRIPTION
**Pull request by TLischkaRemerge**
[A previous PR](https://github.com/discourse/prometheus_exporter/pull/208) added the option to define a class method on Sidekiq worker classes. One thing that was accidentally left out is the ability for this function to use the arguments to an individual job run to generate the custom labels. I changed the code to pass the jobs hash to the custom_labels class function if it is defined.

The hash only gets passed if the custom_labels function expects > 0 arguments. This avoids a breaking change with the previous version where a custom_labels function on a worker class didn't take any arguments.

### CODE REVIEW

**Comment by SamSaffron** [comment]
the arity check does make me a bit nervous, can we put a TODO in the code base to remove it at some point?

**Comment by TLischkaRemerge** [comment]
I know what you mean, I also felt quite apprehensive about adding it but I wasn't sure how to avoid a breaking change otherwise. Another option could be to leave it until the next major version is being prepared. Then it could just be a breaking change rather than having the workaround in place. What do you think?

**Comment by SamSaffron** [comment]
I am ok just to keep the awkward  for now as long as you add a `#TODO remove when version X is released`

**Comment by TLischkaRemerge** [comment]
I put a TODO comment to remove the arity check in the next major version: 3.0.0 Sorry it took a long time to get back to you on this one, caught covid in the meantime 😷

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
Thanks @TLischkaRemerge

**Pull request merged**
