### PR TITLE
Active record collector

### LINKED ISSUE #93: Feature Request: ActiveRecord Connection Pool Stats
Hello,

Want to request instrumentation for collecting ActiveRecord connection pool stats.

Method to get stats is `ActiveRecord::Base.connection_pool.stat`. [Documentation here ](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#method-i-stat)

This has to be collected at worker level in cluster mode and at master level in single process mode.

### PR DESCRIPTION
**Pull request by vijayanandnandam**
Resolves #93 

Sample metrics
```
# HELP ruby_active_record_connection_pool_connections Total connections in pool
# TYPE ruby_active_record_connection_pool_connections gauge
ruby_active_record_connection_pool_connections{type="puma_single",pool_name="primary",dbconfig_database="db1",dbconfig_username="db1user",pid="24114"} 0
ruby_active_record_connection_pool_connections{type="sidekiq",pool_name="primary",dbconfig_database="epdb",dbconfig_host="127.0.0.1",pid="24112"} 0

# HELP ruby_active_record_connection_pool_busy Connections in use in pool
# TYPE ruby_active_record_connection_pool_busy gauge
ruby_active_record_connection_pool_busy{type="puma_single",pool_name="primary",dbconfig_database="db1",dbconfig_username="db1user",pid="24114"} 0
ruby_active_record_connection_pool_busy{type="sidekiq",pool_name="primary",dbconfig_database="epdb",dbconfig_host="127.0.0.1",pid="24112"} 0

# HELP ruby_active_record_connection_pool_dead Dead connections in pool
# TYPE ruby_active_record_connection_pool_dead gauge
ruby_active_record_connection_pool_dead{type="puma_single",pool_name="primary",dbconfig_database="db1",dbconfig_username="db1user",pid="24114"} 0
ruby_active_record_connection_pool_dead{type="sidekiq",pool_name="primary",dbconfig_database="epdb",dbconfig_host="127.0.0.1",pid="24112"} 0

# HELP ruby_active_record_connection_pool_idle Idle connections in pool
# TYPE ruby_active_record_connection_pool_idle gauge
ruby_active_record_connection_pool_idle{type="puma_single",pool_name="primary",dbconfig_database="db1",dbconfig_username="db1user",pid="24114"} 0
ruby_active_record_connection_pool_idle{type="sidekiq",pool_name="primary",dbconfig_database="epdb",dbconfig_host="127.0.0.1",pid="24112"} 0

# HELP ruby_active_record_connection_pool_waiting Connection requests waiting
# TYPE ruby_active_record_connection_pool_waiting gauge
ruby_active_record_connection_pool_waiting{type="puma_single",pool_name="primary",dbconfig_database="db1",dbconfig_username="db1user",pid="24114"} 0
ruby_active_record_connection_pool_waiting{type="sidekiq",pool_name="primary",dbconfig_database="epdb",dbconfig_host="127.0.0.1",pid="24112"} 0

# HELP ruby_active_record_connection_pool_size Maximum allowed connection pool size
# TYPE ruby_active_record_connection_pool_size gauge
ruby_active_record_connection_pool_size{type="puma_single",pool_name="primary",dbconfig_database="db1",dbconfig_username="db1user",pid="24114"} 5
ruby_active_record_connection_pool_size{type="sidekiq",pool_name="primary",dbconfig_database="epdb",dbconfig_host="127.0.0.1",pid="24112"} 30
```

### CODE REVIEW

**Comment by SamSaffron** [comment]
What a wonderful PR, well documented and tested. 

Thank you!

**Comment by SamSaffron** [comment]
only including pid here is a bit thin, we probably want a "Type" like sidekiq, web, unicorn master and so on. We got to explain how to do that. 

Also I recommend you have a quick look at Discourse cause we deal with a multi pool scenario. see: https://github.com/discourse/discourse-prometheus/blob/4010dc0f18006f425ccd9500e8a72df82ae628e7/lib/reporter/process.rb#L82-L93

**Comment by vijayanandnandam** [comment]
@SamSaffron 

- Handled Multiple ConnectionPool Scenarios
- Added more docs on how to inject custom labels
- Added options to inject db config into labels

**Comment by vijayanandnandam** [comment]
@samsaffron I am not sure how to test the instrumentation part. Does testing it with sqlite makes sense?

**Comment by SamSaffron** [comment]
I am comfortable with this level of testing for now, if you feel like testing with sqlite though in an integration test with a followup PR I would be happy. 

very tidy change, thanks!

**Pull request merged**
